### PR TITLE
deps: webpack v5 tooling + polyfill and import fixes

### PR DESCRIPTION
**Pull request by thewarman**
### What does this do?
Follow up to #1471. Rebased.

Upgrades `react-scripts` and `craco` to webpack v5 based versions. v5 webpack no longer polyfills node.js dependencies so they have to be manually specified.

Relevant docs on polyfill / resolve.fallback:
- https://webpack.js.org/configuration/resolve/#resolvefallback
- https://web3auth.io/docs/troubleshooting/webpack-issues#react-create-react-app
- https://docs.cloud.coinbase.com/wallet-sdk/docs/web3-react

`react-scripts` now also generates noisy warnings about source maps in node_modules so we silence that warning.
- https://github.com/facebook/create-react-app/discussions/11767

Other changes include updating `web3-utils` as previous version did not correctly export a default object. This small change is here in this [commit](https://github.com/zer0-os/zOS/pull/1466/commits/131e7a72cba2d6bb97b21c3b820a74a1a3333852).

### Why are we making this change?
In preparation for required toolchain dependencies for Electron desktop app.

### How do I test this?
Run development / tests as usual.

#### Things to consider:
  1. How will this affect security?
  1. How will this affect performance?
  1. Does this change any APIs?

### CODE REVIEW

**Comment by thewarman** [comment]
@dalefukami Rebased and updated with fix for the babel warning.

**Comment by dalefukami** [comment]
alright, I pinned the `remark-emoji` lib to the previously known working version. I'm getting test failures and the app itself doesn't even seem to load.

**Comment by dalefukami** [comment]
> What other issues are you seeing?
1. I run the tests and they fail
2. I open the app and it errors: `DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/index.57b929938b60f812202d.cjs') is not a valid name.`

**Comment by dalefukami** [comment]
A number of these issues appear to be because we updated the entire `package-lock` file. Is there a specific reason we had to do that? I.E., why not just add our dependencies and just npm install as usual?

**Comment by thewarman** [comment]
> A number of these issues appear to be because we updated the entire `package-lock` file. Is there a specific reason we had to do that? I.E., why not just add our dependencies and just npm install as usual?

🤔 That is what I did but maybe something went wrong when resolving conflicts during rebase.

**Comment by dalefukami** [comment]
It looks like you deleted the package-lock file and regenerated it from scratch. The `lockfileVersion` changed and that's usually a sign that it was started from empty again.

**Comment by thewarman** [comment]
Locally - almost all appear to be timeout related to the use of `jest.useFakeTimers()` and `jest.runAllTimers()`. The tests pass (I think?) but just with long delay. There might be change in behavior of how these timer functions work.

```
Test Suites: 2 failed, 146 passed, 148 total
Tests:       14 failed, 4 skipped, 1162 passed, 1180 total
Snapshots:   0 total
Time:        84.902 s
Ran all test suites.
```

**Comment by dalefukami** [comment]
Alright, I think we're probably in a position to merge this next Tuesday. Can you have all the conflicts resolved and ready to go on Tuesday morning and then we can manage this merge throughout the day.

**Pull request merged**
