### PR TITLE
feat: conversation header alignment and style

### PR DESCRIPTION
**Pull request by domw30**
### What does this do?
- Alters the conversations headers to use the same text, icon size and positioning to ensure a smooth transition between the stages of a flow.
- Hides the Rewards Bar when starting one of the flows i.e. starting a group converstation.
- Updates the tests.

### Why are we making this change?
- Right now, when creating a new conversation in the app, the position of the header shifts. See the attached gif for an illustration of the difference in positioning between “Conversations” and “New Message.”

### How do I test this?
- open messenger and in the sidekick panel check the panel header when navigating through stages

#### Things to consider:
  1. How will this affect security?
  1. How will this affect performance?
  1. Does this change any APIs?

https://github.com/zer0-os/zOS/assets/39112648/36f02cb0-4531-46bf-b5c3-2da333ba584a

### CODE REVIEW

**Comment by dalefukami** [comment]
Is this meant to be stacked on top of the previous PR?

**Comment by domw30** [comment]
> Is this meant to be stacked on top of the previous PR?

Yes. Haven't request review here yet

**Comment by dalefukami** [comment]
oh, it's not marked as a draft so that implies it's ready.

**Comment by dalefukami** [comment]
If it's ready enough for review you can just make the base branch to be your refactoring branch. That allows review to continue and then once you've merged the refactoring branch this one will just update automatically.

**Comment by domw30** [comment]
Merge conflicts fixed. Ready for review. Thanks team!

**Pull request merged**
